### ISSUE TITLE
segmentation fault on Mac

### ISSUE THREAD

**Issue by wenxiwu777** [linusmossberg/monte-carlo-ray-tracer#1]
hi, when i run this ray tracer through command line on mac, it always prompts "zsh: segmentation fault", then the program aborts without result image.Anyone has the same problem like this one?

**Comment by wenxiwu777** [comment]
and it has already passed the option selection phase, seemingly to begin to render.

**Comment by linusmossberg** [comment]
Thanks for letting me know! I have only tested the program on Linux and Windows. What compiler and compiler options do you use?

**Comment by wenxiwu777** [comment]
hi, i debugged on it with different scenes, the program crashed at the same line, in function, Image::getExposure()
histogram[static_cast<size_t>(std::floor(t / bin_size))]++;
and i changed the initial size of the histogram, like std::vector<size_t> histogram(65535, 0); 
it can work now, a bit weird, or i set the "plain" to true, it can also work well.

Thank you for this amazing ray tracer, the rendering quality is high, and where can i obtain the "frosted dragon scene" and "caustics scene" ? thx.

**Comment by wenxiwu777** [comment]
i use the default settings of the scene file, but there are lots of noise in the result image, is the 'sqrtspp' too small or something? 
i rendered the following image with metals.json, the 'sqrtspp' is 10.
![metals](https://user-images.githubusercontent.com/25416069/88623982-ba940e80-d0d8-11ea-8388-28966fd4a68a.png)

**Comment by linusmossberg** [comment]
I see, thanks! It seems like the edge case `t / bin_size == histogram.size()` could be the issue. Strange that this never happens when using full optimization with GCC/MSVC though. It should be fixed now anyhow, could you confirm that it works?

The frosted dragon scene is the `stanford_dragon.json` scene. The caustics scene is very large and requires 32 GB RAM + 32 GB virtual memory for the same results so I didn't include it, but here's a download link: https://drive.google.com/file/d/14m97uBnIl8D5P87NVuY2cyn55Sz0DXwA/view?usp=sharing 
You may want to reduce photon emissions and the caustic factor to reduce memory requirements.

That looks normal for 10 sqrtspp, the final image was rendered with 512 sqrtspp. Microfacet specular effects takes a long time to converge with small light sources.

**Comment by wenxiwu777** [comment]
hi, i tested it several other times with the old version of code, i confirmed the problem on my machine, i use qt creator as my IDE and i noticed that it can only allow apple clang as its compiler on mac(already in optimization mode), i haven't tested other IDEs yet, so i guess its only the matters of clang.
I updated the code, and now the problem is gone.

The caustics scene is memory killer, i'd have to stop doing it, but the wave.obj is interesting, i'd like to see what it looks like.

I guess its the problem of path tracer itself, it usually needs a large amount of sample pixels and takes long time to render scenes.

**Comment by wenxiwu777** [comment]
The problem has been solved, thank you.

**Comment by linusmossberg** [comment]
Thanks for confirming! 

Yeah, I believe that more recent versions of photon mappning such as "Stochastic Progressive Photon Mapping" addresses this memory issue. It's possible to get decent results very fast with `"emissions": 1e6"`, `"caustic_factor": 10` and `"sqrtspp": 4` though. The original scene with a smaller water mesh is available here: https://benedikt-bitterli.me/resources/

Yeah, path tracing is slow. There are better sampling techniques and fast ray intersection libraries such as Intel Embree though. The tungsten renderer is one of the more optimized CPU renderers I believe: https://github.com/tunabrain/tungsten

**Comment by wenxiwu777** [comment]
Thank you for sharing, it's very helpful, i've read some about SPPM, it's a bit complex for me now, but it's worth studying, i think your code is a good place to get started. :)
