### ISSUE TITLE
ls.bsdf_pdf is not assigned

### ISSUE THREAD

**Issue by wenxiwu777** [linusmossberg/monte-carlo-ray-tracer#3]
HI, Linus,
I have a question in your new version of the code.
In PathTracer::sampleRay, ls.bsdf_pdf is 0.0 when the sampleEmissive is called, thus powerHeuristic always returns zero. I 
doubt if it is the case.
Thanks.

**Comment by linusmossberg** [comment]
Hi Wenxi!

`ls.bsdf_pdf` is passed to `Interaction::sampleBSDF` as reference in `PathTracer::sampleRay`, which then is passed to the second overloaded `Interaction::BSDF` as reference, where it is set to the true PDF of the importance sampled ray. So it is 0 when `Integrator::sampleEmissive` is called in the first iteration, but this is correct since the ray originated from the camera and not a surface scatter. 

`Integrator::sampleEmissive` checks for this using `interaction.ray.depth == 0`, in which case MIS is not used since we couldn't have sampled a light source in the previous iteration using `Integrator::sampleDirect` (since there was no previous iteration). 

Performing MIS this way is a bit confusing compared to trying both the light and BSDF sampling strategies at the same time when evaluating direct light like pbrt-v3, but it is more efficient since we don't have to cast an additional ray each iteration.

I think that pbrt-v4 has moved to this method as well judging by the following from the readme:

> A single ray is now traced for both indirect lighting and BSDF-sampled direct-lighting.

I learned about this method from [GLSL-PathTracer](https://github.com/knightcrawler25/GLSL-PathTracer) and possibly [Tinsel](https://github.com/mmacklin/tinsel) if I recall correctly, so you may look at those as well.

**Comment by wenxiwu777** [comment]
Oh, I see, I may not get it previously. :)
I didn't notice the fact that at the time when the powerHeuristic is called the ls.bsdf_pdf is already assigned in the overloaded version of BSDF with six parameters, because if the ray hits the emissive surface in the first time the depth is 0 in that case the second condition won't be reached, but in the following paths the MIS between light source and material surface can be performed.

I haven't read pbrt-v4 code for now, I will learn it later as well as other resources you provided here.

Thank you for your reply.

**Comment by linusmossberg** [comment]
Exactly!
